FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Person.Api/Person.Api.csproj", "Person.Api/"]
RUN dotnet restore "Person.Api/Person.Api.csproj"
COPY . .
WORKDIR "/src/Person.Api"
RUN dotnet build "Person.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Person.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Person.Api.dll"]
