version: '3.3'

services:
  garage:
    container_name: 'garage-api'
    build:
      context: './Garage.Api'
    ports:
      - "7220:80"
  person:
    container_name: 'person-api'
    build:
      context: './Person.Api'
    ports:
      - "7221:80"